package entities;
// Generated 25 ene 2025, 23:51:06 by Hibernate Tools 5.6.15.Final

/**
 * Registros generated by hbm2java
 */
public class Registros implements java.io.Serializable {

	private String numRegistro;
	private String dni;
	private String nombre;
	private String apellidos;
	private String tramite;
	private String entidad;

	public Registros() {
	}

	public Registros(String dni, String nombre, String apellidos, String tramite, String entidad) {
		this.dni = dni;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.tramite = tramite;
		this.entidad = entidad;
	}

	public String getNumRegistro() {
		return this.numRegistro;
	}

	public void setNumRegistro(String numRegistro) {
		this.numRegistro = numRegistro;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getTramite() {
		return this.tramite;
	}

	public void setTramite(String tramite) {
		this.tramite = tramite;
	}

	public String getEntidad() {
		return this.entidad;
	}

	public void setEntidad(String entidad) {
		this.entidad = entidad;
	}

}
