package entities;
// Generated 10 ene 2025, 11:50:58 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos implements java.io.Serializable {

	private int dptoNo;
	private String dnombre;
	private Set empleadoses = new HashSet(0);

	public Departamentos() {
	}

	public Departamentos(int dptoNo) {
		this.dptoNo = dptoNo;
	}

	public Departamentos(int dptoNo, String dnombre, Set empleadoses) {
		this.dptoNo = dptoNo;
		this.dnombre = dnombre;
		this.empleadoses = empleadoses;
	}

	public int getDptoNo() {
		return this.dptoNo;
	}

	public void setDptoNo(int dptoNo) {
		this.dptoNo = dptoNo;
	}

	public String getDnombre() {
		return this.dnombre;
	}

	public void setDnombre(String dnombre) {
		this.dnombre = dnombre;
	}

	public Set getEmpleadoses() {
		return this.empleadoses;
	}

	public void setEmpleadoses(Set empleadoses) {
		this.empleadoses = empleadoses;
	}

}
