package entities;
// Generated 10 ene 2025, 11:50:58 by Hibernate Tools 6.5.1.Final

/**
 * Empleados generated by hbm2java
 */
public class Empleados implements java.io.Serializable {

	private int empNo;
	private Departamentos departamentos;
	private String nombre;
	private String apellidos;
	private String oficio;
	private double salario;

	public Empleados() {
	}

	public Empleados(int empNo, Departamentos departamentos, String nombre, String apellidos, String oficio,
			double salario) {
		this.empNo = empNo;
		this.departamentos = departamentos;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.oficio = oficio;
		this.salario = salario;
	}

	public int getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(int empNo) {
		this.empNo = empNo;
	}

	public Departamentos getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Departamentos departamentos) {
		this.departamentos = departamentos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getOficio() {
		return this.oficio;
	}

	public void setOficio(String oficio) {
		this.oficio = oficio;
	}

	public double getSalario() {
		return this.salario;
	}

	public void setSalario(double salario) {
		this.salario = salario;
	}

}
